### ISSUE TITLE
Unable to download the pdf

### ISSUE THREAD

**Issue by shaimei0309** [thunlp/BMCourse#1]
Slide目录下的PDF不能显示，无法下载。已经用了专门的上网线路，git的其它页面均正常。
谢谢🙏

**Comment by ShengdingHu** [comment]
应该至少电脑端是能下载和显示的，可以再研究一下

**Comment by shaimei0309** [comment]
问题补充：使用Chrome浏览器103.0.5060.66，在3天里尝试过至少10次，不能单独下载PDF文档。采用昨天群里所述“大力出奇迹”的办法可以下载全部资料。请指教

**Comment by prnake** [comment]
> 问题补充：使用Chrome浏览器103.0.5060.66，在3天里尝试过至少10次，不能单独下载PDF文档。采用昨天群里所述“大力出奇迹”的办法可以下载全部资料。请指教

试试右键链接另存为，有可能chrome的安全机制把下载的文件拦截了

**Comment by zhangyipeng1** [comment]
我也一样，显示Unable to render code block，应该怎么解决呢？

**Comment by passengeryjy** [comment]
附议

**Comment by passengeryjy** [comment]
> 我也一样，显示Unable to render code block，应该怎么解决呢？

我昨天也是如此，今天搭上梯子访问结果可以下载了 ，但是感觉不是挂梯子的原因，你可以再试试

**Comment by shaimei0309** [comment]
> > 问题补充：使用Chrome浏览器103.0.5060.66，在3天里尝试过至少10次，不能单独下载PDF文档。采用昨天群里所述“大力出奇迹”的办法可以下载全部资料。请指教
> 
> 试试右键链接另存为，有可能chrome的安全机制把下载的文件拦截了

这个办法真的可行，感谢！

**Comment by ShengdingHu** [comment]
如果大家还有下载问题，可以试试直接 git clone呢~
