### ISSUE TITLE
作业2 tie_weights参数

### ISSUE THREAD

**Issue by kcxz** [thunlp/BMCourse#3]
在作业2的参考代码pdf中，`Model.py` 文件里第9行：
```python3
def __init__(self, rnn_type, ntoken, ninp, nhid, nlayers, dropout=0.5, tie_weights=False):
```
在代码中的其他地方没有看到 `tie_weights` 参数。在图片中，`tie_weights`的颜色为深蓝色，比旁边的淡蓝色的颜色更深，好像vs code用此方法表明此参数没有使用。
**请问如果使用此参数，应该在参考代码的哪个地方添加相应代码，以及此参数的作用是什么。**

在 `Main.py`文件里第96行：
```python3
model = model.RNNModel(args.model, ntokens, args.emsize, args.nhid, args.nlayers, args.dr
```
猜想图片右边的缺失部分为：
```python3
opout, args.tied)
```
`Main.py` 文件里第36行对于 `tied` 的描述为：
`tie the word embedding and softmax weights`

在网上搜索 `RNN tie_weights` 关键字，前几个结果中的代码为：
```python3
        # Optionally tie weights as in:
        # "Using the Output Embedding to Improve Language Models" (Press & Wolf 2017)
        # https://arxiv.org/abs/1608.05859
        # and
        # "Tying Word Vectors and Word Classifiers:
        # A Loss Framework for Language Modeling" (Inan et al. 2017)
        # https://arxiv.org/abs/1611.01462
        if tie_weights:
            if nhid != ninp:
                raise ValueError('When using the tied flag, nhid must be equal to emsize')
            self.decoder.weight = self.encoder.weight
```

**Comment by yijing16** [comment]
> 在作业2的参考代码pdf中，`Model.py` 文件里第9行：
> 
> ```python
> def __init__(self, rnn_type, ntoken, ninp, nhid, nlayers, dropout=0.5, tie_weights=False):
> ```
> 
> 在代码中的其他地方没有看到 `tie_weights` 参数。在图片中，`tie_weights`的颜色为深蓝色，比旁边的淡蓝色的颜色更深，好像vs code用此方法表明此参数没有使用。 **请问如果使用此参数，应该在参考代码的哪个地方添加相应代码，以及此参数的作用是什么。**
> 
> 在 `Main.py`文件里第96行：
> 
> ```python
> model = model.RNNModel(args.model, ntokens, args.emsize, args.nhid, args.nlayers, args.dr
> ```
> 
> 猜想图片右边的缺失部分为：
> 
> ```python
> opout, args.tied)
> ```
> 
> `Main.py` 文件里第36行对于 `tied` 的描述为： `tie the word embedding and softmax weights`
> 
> 在网上搜索 `RNN tie_weights` 关键字，前几个结果中的代码为：
> 
> ```python
>         # Optionally tie weights as in:
>         # "Using the Output Embedding to Improve Language Models" (Press & Wolf 2017)
>         # https://arxiv.org/abs/1608.05859
>         # and
>         # "Tying Word Vectors and Word Classifiers:
>         # A Loss Framework for Language Modeling" (Inan et al. 2017)
>         # https://arxiv.org/abs/1611.01462
>         if tie_weights:
>             if nhid != ninp:
>                 raise ValueError('When using the tied flag, nhid must be equal to emsize')
>             self.decoder.weight = self.encoder.weight
> ```

此参数的作用是限制nhid== ninp，也即限定embedding维度和rnn隐层维度一致，使用方法即为同学搜索到的这一段，
mian.py里缺失的一段确是opout, args.tied)

**Comment by yijing16** [comment]
> 在作业2的参考代码pdf中，`Model.py` 文件里第9行：
> 
> ```python
> def __init__(self, rnn_type, ntoken, ninp, nhid, nlayers, dropout=0.5, tie_weights=False):
> ```
> 
> 在代码中的其他地方没有看到 `tie_weights` 参数。在图片中，`tie_weights`的颜色为深蓝色，比旁边的淡蓝色的颜色更深，好像vs code用此方法表明此参数没有使用。 **请问如果使用此参数，应该在参考代码的哪个地方添加相应代码，以及此参数的作用是什么。**
> 
> 在 `Main.py`文件里第96行：
> 
> ```python
> model = model.RNNModel(args.model, ntokens, args.emsize, args.nhid, args.nlayers, args.dr
> ```
> 
> 猜想图片右边的缺失部分为：
> 
> ```python
> opout, args.tied)
> ```
> 
> `Main.py` 文件里第36行对于 `tied` 的描述为： `tie the word embedding and softmax weights`
> 
> 在网上搜索 `RNN tie_weights` 关键字，前几个结果中的代码为：
> 
> ```python
>         # Optionally tie weights as in:
>         # "Using the Output Embedding to Improve Language Models" (Press & Wolf 2017)
>         # https://arxiv.org/abs/1608.05859
>         # and
>         # "Tying Word Vectors and Word Classifiers:
>         # A Loss Framework for Language Modeling" (Inan et al. 2017)
>         # https://arxiv.org/abs/1611.01462
>         if tie_weights:
>             if nhid != ninp:
>                 raise ValueError('When using the tied flag, nhid must be equal to emsize')
>             self.decoder.weight = self.encoder.weight
> ```

此参数的作用是限制nhid== ninp，也即限定embedding维度和rnn隐层维度一致，使用方法即为同学搜索到的这一段，
mian.py里缺失的一段确是opout, args.tied)
